### ISSUE TITLE
how to "unmake" alias created by this utility /  AppleScript?

### ISSUE THREAD

**Issue by Kamillaova** [vs49688/mkalias#1]
I can't figure out if it's correct to use `rm` or not. It looks like this alias might be in the index or something like that

**Comment by vs49688** [comment]
I'm not entirely sure either tbh. I think an alias is just a fat symlink with some extra logic, so `rm` should be fine. At least, that's how I've always done it :shrug:

**Comment by Kamillaova** [comment]
> At least, that's how I've always done it

okay, thanks!
